//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLMigration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string CommitStep {
            get {
                return ResourceManager.GetString("CommitStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadData.
        /// </summary>
        internal static string ConnectionStringKey {
            get {
                return ResourceManager.GetString("ConnectionStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	&apos;&lt;Product&gt;&apos;+
        ///	-- Raw Product data
        ///	(select PC1.IDProdotto,codpro as &apos;Code&apos;, DESCPRO as &apos;Description&apos; from eice.ProdottiCodificati PC1 where PC1.IDProdotto=PC.IDProdotto for XML path(&apos;Data&apos;)) +
        ///	-- Product&apos;s attributes
        ///	(select P.Description as &apos;Key&apos;, RTRIM(PV.Description) as &apos;Value&apos; 
        ///		from eice.ProprietaSintesi PS
        ///		inner join eice.ProprietaValori PV on PV.IDValore = PS.IDValore
        ///		inner join eice.Proprieta P on P.IDProprieta = PV.IDProprieta
        ///		where PS.IDProdotto=PC.IDProdotto AND ISNULL( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialPopulate {
            get {
                return ResourceManager.GetString("InitialPopulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///	&apos;&lt;Product&gt;&apos;+
        ///	-- Raw Product data
        ///	(select PC1.IDProdotto,codpro as &apos;Code&apos;, DESCPRO as &apos;Description&apos; from eice.ProdottiCodificati PC1 where PC1.IDProdotto=PC.IDProdotto for XML path(&apos;Data&apos;)) +
        ///	-- Product&apos;s attributes
        ///	(select P.Description as &apos;Key&apos;, PV.Description as &apos;Value&apos; 
        ///		from eice.ProprietaSintesi PS
        ///		inner join eice.ProprietaValori PV on PV.IDValore = PS.IDValore
        ///		inner join eice.Proprieta P on P.IDProprieta = PV.IDProprieta
        ///		where PS.IDProdotto=PC.IDProdotto for XML path(&apos;Attri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oldQuery {
            get {
                return ResourceManager.GetString("oldQuery", resourceCulture);
            }
        }
    }
}
